// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutxtfst4xFparI3f_6rifMVnz3Nrtvg8',
    appId: '1:711713879681:web:5a5ef4fae5958af8087f80',
    messagingSenderId: '711713879681',
    projectId: 'zeptoclone-dd09b',
    authDomain: 'zeptoclone-dd09b.firebaseapp.com',
    storageBucket: 'zeptoclone-dd09b.appspot.com',
    measurementId: 'G-JZVN2R18YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-9L1L1Qdo83u-4Xd4oMZOHumg-qAaD4',
    appId: '1:711713879681:android:6a08ff5ade808197087f80',
    messagingSenderId: '711713879681',
    projectId: 'zeptoclone-dd09b',
    storageBucket: 'zeptoclone-dd09b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Epu3LbyqN2nFwg5VSBNGFrjMOU3JuRY',
    appId: '1:711713879681:ios:e678a925a277d061087f80',
    messagingSenderId: '711713879681',
    projectId: 'zeptoclone-dd09b',
    storageBucket: 'zeptoclone-dd09b.appspot.com',
    iosBundleId: 'com.example.clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Epu3LbyqN2nFwg5VSBNGFrjMOU3JuRY',
    appId: '1:711713879681:ios:e678a925a277d061087f80',
    messagingSenderId: '711713879681',
    projectId: 'zeptoclone-dd09b',
    storageBucket: 'zeptoclone-dd09b.appspot.com',
    iosBundleId: 'com.example.clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutxtfst4xFparI3f_6rifMVnz3Nrtvg8',
    appId: '1:711713879681:web:be4d13f6cad9bbbb087f80',
    messagingSenderId: '711713879681',
    projectId: 'zeptoclone-dd09b',
    authDomain: 'zeptoclone-dd09b.firebaseapp.com',
    storageBucket: 'zeptoclone-dd09b.appspot.com',
    measurementId: 'G-QR0TXHC7T3',
  );
}
